import { useState, useEffect } from 'react';

export const mockData = [
  {
    id: 1,
    title: 'Разработка мобильного приложения',
    description:
      'Создание кроссплатформенного приложения для доставки еды с системой оплаты и трекингом заказов',
    status: 'active',
    createdAt: '2024-01-15',
    owner: 'Иван Петров',
    priority: 'high',
    deadline: '2024-03-30',
    budget: '1 200 000 ₽',
    team: [
      'Фронтенд разработчик',
      'Бэкенд разработчик',
      'UI/UX дизайнер',
      'Тестировщик',
    ],
    technologies: ['React Native', 'Node.js', 'MongoDB', 'Firebase'],
    progress: 65,
    tasksCompleted: 23,
    totalTasks: 35,
    lastUpdate: '2024-02-15',
    client: 'FoodDelivery Inc.',
    requirements: [
      'Поддержка iOS/Android',
      'Интеграция с платежными системами',
      'Реальное время отслеживания заказов',
    ],
    goal: 'Запуск приложения в AppStore и Google Play с показателем 4.5+ звезд и 10K+ установок в первый месяц',
  },
  {
    id: 2,
    title: 'Редизайн корпоративного сайта',
    description:
      'Обновление UI/UX дизайна и улучшение пользовательского опыта для увеличения конверсии',
    status: 'completed',
    createdAt: '2024-01-10',
    owner: 'Мария Сидорова',
    priority: 'medium',
    deadline: '2024-02-28',
    budget: '450 000 ₽',
    team: ['UI/UX дизайнер', 'Верстальщик', 'Копирайтер'],
    technologies: ['Figma', 'React', 'SASS', 'WordPress'],
    progress: 100,
    tasksCompleted: 42,
    totalTasks: 42,
    lastUpdate: '2024-02-25',
    client: 'ТехноКорп',
    requirements: [
      'Адаптивный дизайн',
      'Увеличение конверсии на 25%',
      'Интеграция с CRM',
    ],
    goal: 'Увеличение конверсии посетителей в лиды на 30% и снижение bounce rate на 15%',
  },
  {
    id: 3,
    title: 'Внедрение CRM системы',
    description:
      'Интеграция и настройка CRM для отдела продаж с автоматизацией процессов',
    status: 'active',
    createdAt: '2024-01-20',
    owner: 'Алексей Козлов',
    priority: 'high',
    deadline: '2024-04-15',
    budget: '800 000 ₽',
    team: ['Бизнес-аналитик', 'CRM специалист', 'Тестировщик'],
    technologies: ['Salesforce', 'REST API', 'PostgreSQL'],
    progress: 40,
    tasksCompleted: 16,
    totalTasks: 40,
    lastUpdate: '2024-02-14',
    client: 'SalesPro Company',
    requirements: [
      'Автоматизация воронки продаж',
      'Интеграция с телефонией',
      'Аналитика и отчетность',
    ],
    goal: 'Сокращение времени обработки заявки с 24 до 4 часов и увеличение конверсии лидов на 40%',
  },
  {
    id: 4,
    title: 'Разработка API для партнеров',
    description:
      'Создание RESTful API для интеграции с системами партнеров и биллинга',
    status: 'in-progress',
    createdAt: '2024-01-25',
    owner: 'Екатерина Новикова',
    priority: 'medium',
    deadline: '2024-03-10',
    budget: '350 000 ₽',
    team: ['Бэкенд разработчик', 'DevOps инженер'],
    technologies: ['Python', 'FastAPI', 'Docker', 'PostgreSQL'],
    progress: 75,
    tasksCompleted: 15,
    totalTasks: 20,
    lastUpdate: '2024-02-18',
    client: 'Партнерская сеть "БизнесКоннект"',
    requirements: [
      'RESTful API',
      'OAuth аутентификация',
      'Документация Swagger',
      'Лимиты запросов',
    ],
    goal: 'Подключение 50+ партнеров через API в течение 6 месяцев и обработка 10K+ запросов в день',
  },
  {
    id: 5,
    title: 'Аналитика и метрики продукта',
    description:
      'Настройка системы сбора аналитики и дашбордов для отслеживания ключевых метрик',
    status: 'planning',
    createdAt: '2024-02-01',
    owner: 'Дмитрий Волков',
    priority: 'low',
    deadline: '2024-05-20',
    budget: '280 000 ₽',
    team: ['Data Analyst', 'Product Manager'],
    technologies: ['Google Analytics', 'Tableau', 'SQL', 'Python'],
    progress: 10,
    tasksCompleted: 2,
    totalTasks: 18,
    lastUpdate: '2024-02-05',
    client: 'Стартап "Инновации"',
    requirements: [
      'Дашборд ключевых метрик',
      'A/B тестирование',
      'Отслеживание конверсии',
      'Автоотчеты',
    ],
    goal: 'Внедрение data-driven культуры принятия решений и увеличение retention rate на 25%',
  },
  {
    id: 6,
    title: 'Миграция в облачную инфраструктуру',
    description:
      'Перенос серверов и приложений в AWS с оптимизацией затрат и повышением отказоустойчивости',
    status: 'active',
    createdAt: '2024-01-18',
    owner: 'Ольга Смирнова',
    priority: 'high',
    deadline: '2024-04-10',
    budget: '950 000 ₽',
    team: ['DevOps инженер', 'Системный администратор', 'Бэкенд разработчик'],
    technologies: ['AWS', 'Terraform', 'Docker', 'Kubernetes'],
    progress: 55,
    tasksCompleted: 22,
    totalTasks: 40,
    lastUpdate: '2024-02-20',
    client: 'FinTech Solutions',
    requirements: [
      'Минимальное время простоя',
      'Автомасштабирование',
      'Резервное копирование',
      'Мониторинг',
    ],
    goal: 'Снижение инфраструктурных затрат на 35% и повышение uptime до 99.9%',
  },
  {
    id: 7,
    title: 'Разработка системы машинного обучения',
    description:
      'Создание ML-модели для прогнозирования спроса и оптимизации складских запасов',
    status: 'in-progress',
    createdAt: '2024-01-30',
    owner: 'Артем Ковалев',
    priority: 'high',
    deadline: '2024-05-15',
    budget: '1 500 000 ₽',
    team: ['Data Scientist', 'ML Engineer', 'Бэкенд разработчик'],
    technologies: ['Python', 'TensorFlow', 'Pandas', 'FastAPI'],
    progress: 30,
    tasksCompleted: 12,
    totalTasks: 40,
    lastUpdate: '2024-02-22',
    client: 'RetailChain Corp',
    requirements: [
      'Точность прогноза >85%',
      'Интеграция с ERP',
      'Реальное время предсказаний',
      'A/B тестирование моделей',
    ],
    goal: 'Снижение излишков запасов на 40% и увеличение оборачиваемости товаров на 25%',
  },
  {
    id: 8,
    title: 'Создание системы электронного документооборота',
    description:
      'Разработка платформы для управления документами с электронной подписью и workflow',
    status: 'active',
    createdAt: '2024-02-05',
    owner: 'Светлана Орлова',
    priority: 'medium',
    deadline: '2024-06-30',
    budget: '680 000 ₽',
    team: ['Fullstack разработчик', 'UI/UX дизайнер', 'Тестировщик'],
    technologies: ['Vue.js', 'Node.js', 'PostgreSQL', 'Redis'],
    progress: 25,
    tasksCompleted: 10,
    totalTasks: 40,
    lastUpdate: '2024-02-28',
    client: 'ГосУниверситет',
    requirements: [
      'Поддержка ЭЦП',
      'Workflow утверждения',
      'Версионность документов',
      'Поиск по содержимому',
    ],
    goal: 'Сокращение времени обработки документов с 5 дней до 1 дня и переход на безбумажный workflow',
  },
  {
    id: 9,
    title: 'Оптимизация производительности веб-приложения',
    description:
      'Анализ и улучшение скорости загрузки и отзывчивости корпоративного портала',
    status: 'completed',
    createdAt: '2024-01-08',
    owner: 'Михаил Белов',
    priority: 'medium',
    deadline: '2024-02-20',
    budget: '320 000 ₽',
    team: ['Frontend разработчик', 'Performance Engineer'],
    technologies: ['React', 'Webpack', 'Lighthouse', 'Chrome DevTools'],
    progress: 100,
    tasksCompleted: 18,
    totalTasks: 18,
    lastUpdate: '2024-02-18',
    client: 'CorporatePortal Ltd',
    requirements: [
      'Lighthouse score >90',
      'TTFB <200ms',
      'Core Web Vitals в зеленой зоне',
      'Кэширование ресурсов',
    ],
    goal: 'Улучшение Core Web Vitals и сокращение времени загрузки на 60%',
  },
  {
    id: 10,
    title: 'Внедрение системы мониторинга и алертинга',
    description:
      'Настройка комплексного мониторинга инфраструктуры и бизнес-метрик с системой оповещений',
    status: 'in-progress',
    createdAt: '2024-02-10',
    owner: 'Денис Морозов',
    priority: 'medium',
    deadline: '2024-04-25',
    budget: '420 000 ₽',
    team: ['DevOps инженер', 'SRE инженер'],
    technologies: ['Prometheus', 'Grafana', 'Alertmanager', 'ELK Stack'],
    progress: 70,
    tasksCompleted: 21,
    totalTasks: 30,
    lastUpdate: '2024-03-01',
    client: 'E-commerce Platform',
    requirements: [
      'Мониторинг 100% компонентов',
      'Автоматическое восстановление',
      'SLA отчетность',
      'Кастомные дашборды',
    ],
    goal: 'Сокращение времени обнаружения инцидентов с 30 минут до 2 минут и повышение SLA до 99.95%',
  },
  {
    id: 11,
    title: 'Разработка PWA для полевых сотрудников',
    description:
      'Создание прогрессивного веб-приложения для работы мобильных сотрудников в офлайн-режиме',
    status: 'active',
    createdAt: '2024-02-12',
    owner: 'Анна Крылова',
    priority: 'high',
    deadline: '2024-05-05',
    budget: '580 000 ₽',
    team: ['Frontend разработчик', 'UI/UX дизайнер', 'Тестировщик'],
    technologies: ['Vue.js', 'PWA', 'IndexedDB', 'Service Workers'],
    progress: 45,
    tasksCompleted: 18,
    totalTasks: 40,
    lastUpdate: '2024-03-02',
    client: 'ServiceCompany Pro',
    requirements: [
      'Офлайн работа',
      'Синхронизация данных',
      'Push уведомления',
      'Кроссплатформенность',
    ],
    goal: 'Повышение эффективности полевых сотрудников на 35% и сокращение бумажного документооборота',
  },
  {
    id: 12,
    title: 'Модернизация legacy системы',
    description:
      'Рефакторинг и обновление устаревшей системы бухгалтерского учета с переносом на современный стек',
    status: 'planning',
    createdAt: '2024-02-15',
    owner: 'Павел Громов',
    priority: 'low',
    deadline: '2024-08-15',
    budget: '1 100 000 ₽',
    team: ['Fullstack разработчик', 'Бизнес-аналитик', 'Тестировщик'],
    technologies: ['Java Spring', 'React', 'PostgreSQL', 'Docker'],
    progress: 5,
    tasksCompleted: 2,
    totalTasks: 50,
    lastUpdate: '2024-02-28',
    client: 'Accounting Firm "Баланс"',
    requirements: [
      'Совместимость с существующими данными',
      'Поэтапный переход',
      'Обучение пользователей',
      'Миграция данных',
    ],
    goal: 'Увеличение производительности системы в 5 раз и снижение затрат на поддержку на 60%',
  },
  {
    id: 13,
    title: 'Создание системы управления знаниями',
    description:
      'Разработка корпоративной базы знаний с AI-поиском и рекомендациями',
    status: 'in-progress',
    createdAt: '2024-02-18',
    owner: 'Елена Соколова',
    priority: 'medium',
    deadline: '2024-06-10',
    budget: '720 000 ₽',
    team: ['Fullstack разработчик', 'AI Engineer', 'UI/UX дизайнер'],
    technologies: ['Python', 'React', 'Elasticsearch', 'ML algorithms'],
    progress: 35,
    tasksCompleted: 14,
    totalTasks: 40,
    lastUpdate: '2024-03-05',
    client: 'Consulting Group "Стратегия"',
    requirements: [
      'Семантический поиск',
      'Персонализированные рекомендации',
      'Аналитика использования',
      'Интеграция с MS Teams',
    ],
    goal: 'Сокращение времени поиска информации на 70% и повышение переиспользования знаний на 50%',
  },
  {
    id: 14,
    title: 'Разработка IoT платформы',
    description:
      'Создание платформы для сбора и анализа данных с IoT устройств умного города',
    status: 'active',
    createdAt: '2024-01-25',
    owner: 'Сергей Павлов',
    priority: 'high',
    deadline: '2024-07-20',
    budget: '2 300 000 ₽',
    team: ['IoT разработчик', 'Data Engineer', 'Backend разработчик', 'DevOps'],
    technologies: ['MQTT', 'Kafka', 'TimescaleDB', 'Grafana'],
    progress: 20,
    tasksCompleted: 15,
    totalTasks: 75,
    lastUpdate: '2024-03-01',
    client: 'SmartCity Administration',
    requirements: [
      'Обработка 1M+ событий в день',
      'Реальное время аналитики',
      'Масштабируемость',
      'Безопасность данных',
    ],
    goal: 'Создание единой платформы для 10K+ IoT устройств и снижение операционных затрат города на 25%',
  },
  {
    id: 15,
    title: 'Внедрение системы управления проектами',
    description:
      'Настройка и кастомизация Jira/Confluence для оптимизации процессов разработки',
    status: 'completed',
    createdAt: '2024-01-12',
    owner: 'Наталья Воробьева',
    priority: 'medium',
    deadline: '2024-02-25',
    budget: '280 000 ₽',
    team: ['Business Analyst', 'Jira Administrator'],
    technologies: ['Jira', 'Confluence', 'ScriptRunner', 'Automation'],
    progress: 100,
    tasksCompleted: 25,
    totalTasks: 25,
    lastUpdate: '2024-02-22',
    client: 'IT Department "Прогресс"',
    requirements: [
      'Кастомные workflow',
      'Интеграция с GitHub',
      'Автоматизация отчетности',
      'Обучение команды',
    ],
    goal: 'Сокращение времени планирования спринтов на 40% и повышение прозрачности разработки',
  },
  {
    id: 16,
    title: 'Создание чат-бота для поддержки клиентов',
    description:
      'Разработка AI-чата для автоматизации ответов на частые вопросы клиентов',
    status: 'in-progress',
    createdAt: '2024-02-20',
    owner: 'Александр Новиков',
    priority: 'medium',
    deadline: '2024-05-30',
    budget: '490 000 ₽',
    team: ['AI Engineer', 'Frontend разработчик', 'Linguist'],
    technologies: ['Python', 'Rasa', 'React', 'NLP'],
    progress: 60,
    tasksCompleted: 18,
    totalTasks: 30,
    lastUpdate: '2024-03-08',
    client: 'Bank "Финансы"',
    requirements: [
      'Точность ответов >90%',
      'Мультиязычность',
      'Эскалация на оператора',
      'Аналитика диалогов',
    ],
    goal: 'Автоматизация 70% запросов поддержки и сокращение времени ответа с 5 минут до 10 секунд',
  },
  {
    id: 17,
    title: 'Миграция на микросервисную архитектуру',
    description:
      'Разделение монолита на микросервисы с внедрением event-driven архитектуры',
    status: 'active',
    createdAt: '2024-02-08',
    owner: 'Виктор Козлов',
    priority: 'high',
    deadline: '2024-09-15',
    budget: '1 800 000 ₽',
    team: ['Backend разработчик', 'DevOps', 'Architect'],
    technologies: ['Kubernetes', 'gRPC', 'Kafka', 'Istio'],
    progress: 15,
    tasksCompleted: 12,
    totalTasks: 80,
    lastUpdate: '2024-03-10',
    client: 'E-commerce Giant',
    requirements: [
      'Zero downtime миграция',
      'Автомасштабирование',
      'Мониторинг',
      'Резервное копирование',
    ],
    goal: 'Увеличение масштабируемости в 10 раз и снижение coupling между командами разработки',
  },
  {
    id: 18,
    title: 'Разработка системы кэширования',
    description:
      'Создание распределенной системы кэширования для высоконагруженного приложения',
    status: 'planning',
    createdAt: '2024-03-01',
    owner: 'Ирина Медведева',
    priority: 'medium',
    deadline: '2024-06-20',
    budget: '380 000 ₽',
    team: ['Backend разработчик', 'DevOps'],
    technologies: ['Redis Cluster', 'Memcached', 'Go', 'Prometheus'],
    progress: 8,
    tasksCompleted: 3,
    totalTasks: 35,
    lastUpdate: '2024-03-12',
    client: 'Social Media Platform',
    requirements: [
      'Latency <1ms',
      '99.99% availability',
      'Автоматическое failover',
      'Мониторинг hit rate',
    ],
    goal: 'Снижение нагрузки на базу данных на 80% и ускорение ответа API в 5 раз',
  },
  {
    id: 19,
    title: 'Создание системы A/B тестирования',
    description:
      'Разработка платформы для проведения экспериментов и анализа их эффективности',
    status: 'in-progress',
    createdAt: '2024-02-25',
    owner: 'Роман Орлов',
    priority: 'medium',
    deadline: '2024-05-15',
    budget: '540 000 ₽',
    team: ['Fullstack разработчик', 'Data Analyst', 'UI/UX дизайнер'],
    technologies: ['React', 'Node.js', 'Statistics', 'Data Visualization'],
    progress: 50,
    tasksCompleted: 20,
    totalTasks: 40,
    lastUpdate: '2024-03-14',
    client: 'Online Marketplace',
    requirements: [
      'Статистическая значимость',
      'Мультивариативное тестирование',
      'Real-time результаты',
      'Интеграция с аналитикой',
    ],
    goal: 'Увеличение конверсии на 15% через data-driven оптимизацию пользовательского опыта',
  },
  {
    id: 20,
    title: 'Внедрение системы управления цифровыми активами',
    description:
      'Создание платформы для управления медиафайлами, документами и цифровым контентом',
    status: 'active',
    createdAt: '2024-02-28',
    owner: 'Марина Федорова',
    priority: 'low',
    deadline: '2024-07-10',
    budget: '620 000 ₽',
    team: ['Fullstack разработчик', 'UI/UX дизайнер', 'DevOps'],
    technologies: ['Vue.js', 'Node.js', 'MongoDB', 'AWS S3'],
    progress: 28,
    tasksCompleted: 11,
    totalTasks: 40,
    lastUpdate: '2024-03-15',
    client: 'Media Agency "Креатив"',
    requirements: [
      'Поддержка 100+ форматов',
      'Автоматическая конвертация',
      'Права доступа',
      'Версионность',
    ],
    goal: 'Сокращение времени поиска и использования цифровых активов на 60% и централизация управления контентом',
  },
];

export const getProjectData = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockData);
    }, 5000);
  });
};

export const useProjects = () => {
  const [projects, setProjects] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadProjects = async () => {
      const data = await getProjectData();
      setProjects(data);
      setLoading(false);
    };
    loadProjects();
  }, []);

  return { projects, loading };
};
