import { useState, useEffect } from 'react';

export const mockData = [
  {
    id: 1,
    title: 'Mobile App Development',
    description:
      'Creating a cross-platform food delivery app with payment system and order tracking',
    status: 'active',
    createdAt: '2024-01-15',
    owner: 'John Smith',
    priority: 'high',
    deadline: '2024-03-30',
    budget: '$15,000',
    team: [
      'Frontend Developer',
      'Backend Developer',
      'UI/UX Designer',
      'QA Tester',
    ],
    technologies: ['React Native', 'Node.js', 'MongoDB', 'Firebase'],
    progress: 65,
    tasksCompleted: 23,
    totalTasks: 35,
    lastUpdate: '2024-02-15',
    client: 'FoodDelivery Inc.',
    requirements: [
      'iOS/Android support',
      'Payment system integration',
      'Real-time order tracking',
    ],
    goal: 'Launch on AppStore and Google Play with 4.5+ star rating and 10K+ downloads in first month',
  },
  {
    id: 2,
    title: 'Corporate Website Redesign',
    description:
      'UI/UX design update and user experience improvement for conversion rate optimization',
    status: 'completed',
    createdAt: '2024-01-10',
    owner: 'Sarah Johnson',
    priority: 'medium',
    deadline: '2024-02-28',
    budget: '$5,600',
    team: ['UI/UX Designer', 'Frontend Developer', 'Copywriter'],
    technologies: ['Figma', 'React', 'SASS', 'WordPress'],
    progress: 100,
    tasksCompleted: 42,
    totalTasks: 42,
    lastUpdate: '2024-02-25',
    client: 'TechCorp Inc.',
    requirements: [
      'Responsive design',
      '25% conversion increase',
      'CRM integration',
    ],
    goal: 'Increase visitor-to-lead conversion by 30% and reduce bounce rate by 15%',
  },
  {
    id: 3,
    title: 'CRM System Implementation',
    description:
      'Integration and configuration of CRM for sales department with process automation',
    status: 'active',
    createdAt: '2024-01-20',
    owner: 'Michael Brown',
    priority: 'high',
    deadline: '2024-04-15',
    budget: '$10,000',
    team: ['Business Analyst', 'CRM Specialist', 'QA Tester'],
    technologies: ['Salesforce', 'REST API', 'PostgreSQL'],
    progress: 40,
    tasksCompleted: 16,
    totalTasks: 40,
    lastUpdate: '2024-02-14',
    client: 'SalesPro Company',
    requirements: [
      'Sales funnel automation',
      'Telephony integration',
      'Analytics and reporting',
    ],
    goal: 'Reduce lead processing time from 24 to 4 hours and increase lead conversion by 40%',
  },
  {
    id: 4,
    title: 'Partner API Development',
    description:
      'Creating RESTful API for partner integration and billing systems',
    status: 'in-progress',
    createdAt: '2024-01-25',
    owner: 'Emily Davis',
    priority: 'medium',
    deadline: '2024-03-10',
    budget: '$4,400',
    team: ['Backend Developer', 'DevOps Engineer'],
    technologies: ['Python', 'FastAPI', 'Docker', 'PostgreSQL'],
    progress: 75,
    tasksCompleted: 15,
    totalTasks: 20,
    lastUpdate: '2024-02-18',
    client: 'Partner Network "BusinessConnect"',
    requirements: [
      'RESTful API',
      'OAuth authentication',
      'Swagger documentation',
      'Rate limiting',
    ],
    goal: 'Connect 50+ partners via API within 6 months and handle 10K+ daily requests',
  },
  {
    id: 5,
    title: 'Product Analytics and Metrics',
    description:
      'Setting up analytics collection system and dashboards for key metrics tracking',
    status: 'planning',
    createdAt: '2024-02-01',
    owner: 'David Wilson',
    priority: 'low',
    deadline: '2024-05-20',
    budget: '$3,500',
    team: ['Data Analyst', 'Product Manager'],
    technologies: ['Google Analytics', 'Tableau', 'SQL', 'Python'],
    progress: 10,
    tasksCompleted: 2,
    totalTasks: 18,
    lastUpdate: '2024-02-05',
    client: 'Startup "Innovation"',
    requirements: [
      'Key metrics dashboard',
      'A/B testing',
      'Conversion tracking',
      'Automated reports',
    ],
    goal: 'Implement data-driven decision culture and increase retention rate by 25%',
  },
  {
    id: 6,
    title: 'Cloud Infrastructure Migration',
    description:
      'Moving servers and applications to AWS with cost optimization and increased reliability',
    status: 'active',
    createdAt: '2024-01-18',
    owner: 'Jennifer Miller',
    priority: 'high',
    deadline: '2024-04-10',
    budget: '$11,900',
    team: ['DevOps Engineer', 'System Administrator', 'Backend Developer'],
    technologies: ['AWS', 'Terraform', 'Docker', 'Kubernetes'],
    progress: 55,
    tasksCompleted: 22,
    totalTasks: 40,
    lastUpdate: '2024-02-20',
    client: 'FinTech Solutions',
    requirements: [
      'Minimal downtime',
      'Auto-scaling',
      'Backup solutions',
      'Monitoring',
    ],
    goal: 'Reduce infrastructure costs by 35% and increase uptime to 99.9%',
  },
  {
    id: 7,
    title: 'Machine Learning System Development',
    description:
      'Creating ML model for demand forecasting and inventory optimization',
    status: 'in-progress',
    createdAt: '2024-01-30',
    owner: 'Robert Taylor',
    priority: 'high',
    deadline: '2024-05-15',
    budget: '$18,800',
    team: ['Data Scientist', 'ML Engineer', 'Backend Developer'],
    technologies: ['Python', 'TensorFlow', 'Pandas', 'FastAPI'],
    progress: 30,
    tasksCompleted: 12,
    totalTasks: 40,
    lastUpdate: '2024-02-22',
    client: 'RetailChain Corp',
    requirements: [
      'Forecast accuracy >85%',
      'ERP integration',
      'Real-time predictions',
      'A/B model testing',
    ],
    goal: 'Reduce excess inventory by 40% and increase inventory turnover by 25%',
  },
  {
    id: 8,
    title: 'Electronic Document Management System',
    description:
      'Developing document management platform with digital signatures and workflow',
    status: 'active',
    createdAt: '2024-02-05',
    owner: 'Jessica Anderson',
    priority: 'medium',
    deadline: '2024-06-30',
    budget: '$8,500',
    team: ['Fullstack Developer', 'UI/UX Designer', 'QA Tester'],
    technologies: ['Vue.js', 'Node.js', 'PostgreSQL', 'Redis'],
    progress: 25,
    tasksCompleted: 10,
    totalTasks: 40,
    lastUpdate: '2024-02-28',
    client: 'State University',
    requirements: [
      'Digital signature support',
      'Approval workflow',
      'Version control',
      'Content search',
    ],
    goal: 'Reduce document processing time from 5 days to 1 day and transition to paperless workflow',
  },
  {
    id: 9,
    title: 'Web Application Performance Optimization',
    description:
      'Analysis and improvement of corporate portal loading speed and responsiveness',
    status: 'completed',
    createdAt: '2024-01-08',
    owner: 'Christopher Martinez',
    priority: 'medium',
    deadline: '2024-02-20',
    budget: '$4,000',
    team: ['Frontend Developer', 'Performance Engineer'],
    technologies: ['React', 'Webpack', 'Lighthouse', 'Chrome DevTools'],
    progress: 100,
    tasksCompleted: 18,
    totalTasks: 18,
    lastUpdate: '2024-02-18',
    client: 'CorporatePortal Ltd',
    requirements: [
      'Lighthouse score >90',
      'TTFB <200ms',
      'Core Web Vitals in green',
      'Resource caching',
    ],
    goal: 'Improve Core Web Vitals and reduce loading time by 60%',
  },
  {
    id: 10,
    title: 'Monitoring and Alerting System Implementation',
    description:
      'Setting up comprehensive infrastructure and business metrics monitoring with alerting',
    status: 'in-progress',
    createdAt: '2024-02-10',
    owner: 'Daniel Thomas',
    priority: 'medium',
    deadline: '2024-04-25',
    budget: '$5,250',
    team: ['DevOps Engineer', 'SRE Engineer'],
    technologies: ['Prometheus', 'Grafana', 'Alertmanager', 'ELK Stack'],
    progress: 70,
    tasksCompleted: 21,
    totalTasks: 30,
    lastUpdate: '2024-03-01',
    client: 'E-commerce Platform',
    requirements: [
      '100% component monitoring',
      'Auto-recovery',
      'SLA reporting',
      'Custom dashboards',
    ],
    goal: 'Reduce incident detection time from 30 minutes to 2 minutes and increase SLA to 99.95%',
  },
  {
    id: 11,
    title: 'PWA for Field Employees',
    description:
      'Creating progressive web app for mobile employees with offline capabilities',
    status: 'active',
    createdAt: '2024-02-12',
    owner: 'Amanda White',
    priority: 'high',
    deadline: '2024-05-05',
    budget: '$7,250',
    team: ['Frontend Developer', 'UI/UX Designer', 'QA Tester'],
    technologies: ['Vue.js', 'PWA', 'IndexedDB', 'Service Workers'],
    progress: 45,
    tasksCompleted: 18,
    totalTasks: 40,
    lastUpdate: '2024-03-02',
    client: 'ServiceCompany Pro',
    requirements: [
      'Offline functionality',
      'Data synchronization',
      'Push notifications',
      'Cross-platform',
    ],
    goal: 'Increase field employee efficiency by 35% and reduce paper documentation',
  },
  {
    id: 12,
    title: 'Legacy System Modernization',
    description:
      'Refactoring and updating outdated accounting system with migration to modern stack',
    status: 'planning',
    createdAt: '2024-02-15',
    owner: 'James Harris',
    priority: 'low',
    deadline: '2024-08-15',
    budget: '$13,750',
    team: ['Fullstack Developer', 'Business Analyst', 'QA Tester'],
    technologies: ['Java Spring', 'React', 'PostgreSQL', 'Docker'],
    progress: 5,
    tasksCompleted: 2,
    totalTasks: 50,
    lastUpdate: '2024-02-28',
    client: 'Accounting Firm "Balance"',
    requirements: [
      'Compatibility with existing data',
      'Phased transition',
      'User training',
      'Data migration',
    ],
    goal: 'Increase system performance by 5x and reduce maintenance costs by 60%',
  },
  {
    id: 13,
    title: 'Knowledge Management System',
    description:
      'Developing corporate knowledge base with AI search and recommendations',
    status: 'in-progress',
    createdAt: '2024-02-18',
    owner: 'Elizabeth Clark',
    priority: 'medium',
    deadline: '2024-06-10',
    budget: '$9,000',
    team: ['Fullstack Developer', 'AI Engineer', 'UI/UX Designer'],
    technologies: ['Python', 'React', 'Elasticsearch', 'ML algorithms'],
    progress: 35,
    tasksCompleted: 14,
    totalTasks: 40,
    lastUpdate: '2024-03-05',
    client: 'Consulting Group "Strategy"',
    requirements: [
      'Semantic search',
      'Personalized recommendations',
      'Usage analytics',
      'MS Teams integration',
    ],
    goal: 'Reduce information search time by 70% and increase knowledge reuse by 50%',
  },
  {
    id: 14,
    title: 'IoT Platform Development',
    description:
      'Creating platform for data collection and analysis from smart city IoT devices',
    status: 'active',
    createdAt: '2024-01-25',
    owner: 'Kevin Lewis',
    priority: 'high',
    deadline: '2024-07-20',
    budget: '$28,750',
    team: ['IoT Developer', 'Data Engineer', 'Backend Developer', 'DevOps'],
    technologies: ['MQTT', 'Kafka', 'TimescaleDB', 'Grafana'],
    progress: 20,
    tasksCompleted: 15,
    totalTasks: 75,
    lastUpdate: '2024-03-01',
    client: 'SmartCity Administration',
    requirements: [
      'Process 1M+ daily events',
      'Real-time analytics',
      'Scalability',
      'Data security',
    ],
    goal: 'Create unified platform for 10K+ IoT devices and reduce city operational costs by 25%',
  },
  {
    id: 15,
    title: 'Project Management System Implementation',
    description:
      'Setting up and customizing Jira/Confluence for development process optimization',
    status: 'completed',
    createdAt: '2024-01-12',
    owner: 'Michelle Walker',
    priority: 'medium',
    deadline: '2024-02-25',
    budget: '$3,500',
    team: ['Business Analyst', 'Jira Administrator'],
    technologies: ['Jira', 'Confluence', 'ScriptRunner', 'Automation'],
    progress: 100,
    tasksCompleted: 25,
    totalTasks: 25,
    lastUpdate: '2024-02-22',
    client: 'IT Department "Progress"',
    requirements: [
      'Custom workflows',
      'GitHub integration',
      'Automated reporting',
      'Team training',
    ],
    goal: 'Reduce sprint planning time by 40% and increase development transparency',
  },
  {
    id: 16,
    title: 'Customer Support Chatbot',
    description:
      'Developing AI chat for automating responses to frequent customer questions',
    status: 'in-progress',
    createdAt: '2024-02-20',
    owner: 'Brian Robinson',
    priority: 'medium',
    deadline: '2024-05-30',
    budget: '$6,125',
    team: ['AI Engineer', 'Frontend Developer', 'Linguist'],
    technologies: ['Python', 'Rasa', 'React', 'NLP'],
    progress: 60,
    tasksCompleted: 18,
    totalTasks: 30,
    lastUpdate: '2024-03-08',
    client: 'Bank "Finance"',
    requirements: [
      'Answer accuracy >90%',
      'Multilingual support',
      'Operator escalation',
      'Dialogue analytics',
    ],
    goal: 'Automate 70% of support requests and reduce response time from 5 minutes to 10 seconds',
  },
  {
    id: 17,
    title: 'Microservices Architecture Migration',
    description:
      'Splitting monolith into microservices with event-driven architecture implementation',
    status: 'active',
    createdAt: '2024-02-08',
    owner: 'Richard Young',
    priority: 'high',
    deadline: '2024-09-15',
    budget: '$22,500',
    team: ['Backend Developer', 'DevOps', 'Architect'],
    technologies: ['Kubernetes', 'gRPC', 'Kafka', 'Istio'],
    progress: 15,
    tasksCompleted: 12,
    totalTasks: 80,
    lastUpdate: '2024-03-10',
    client: 'E-commerce Giant',
    requirements: [
      'Zero downtime migration',
      'Auto-scaling',
      'Monitoring',
      'Backup solutions',
    ],
    goal: 'Increase scalability by 10x and reduce coupling between development teams',
  },
  {
    id: 18,
    title: 'Caching System Development',
    description:
      'Creating distributed caching system for high-load application',
    status: 'planning',
    createdAt: '2024-03-01',
    owner: 'Patricia King',
    priority: 'medium',
    deadline: '2024-06-20',
    budget: '$4,750',
    team: ['Backend Developer', 'DevOps'],
    technologies: ['Redis Cluster', 'Memcached', 'Go', 'Prometheus'],
    progress: 8,
    tasksCompleted: 3,
    totalTasks: 35,
    lastUpdate: '2024-03-12',
    client: 'Social Media Platform',
    requirements: [
      'Latency <1ms',
      '99.99% availability',
      'Auto failover',
      'Hit rate monitoring',
    ],
    goal: 'Reduce database load by 80% and speed up API response by 5x',
  },
  {
    id: 19,
    title: 'A/B Testing System',
    description:
      'Developing platform for conducting experiments and analyzing effectiveness',
    status: 'in-progress',
    createdAt: '2024-02-25',
    owner: 'Jason Scott',
    priority: 'medium',
    deadline: '2024-05-15',
    budget: '$6,750',
    team: ['Fullstack Developer', 'Data Analyst', 'UI/UX Designer'],
    technologies: ['React', 'Node.js', 'Statistics', 'Data Visualization'],
    progress: 50,
    tasksCompleted: 20,
    totalTasks: 40,
    lastUpdate: '2024-03-14',
    client: 'Online Marketplace',
    requirements: [
      'Statistical significance',
      'Multivariate testing',
      'Real-time results',
      'Analytics integration',
    ],
    goal: 'Increase conversion by 15% through data-driven user experience optimization',
  },
  {
    id: 20,
    title: 'Digital Asset Management System',
    description:
      'Creating platform for managing media files, documents and digital content',
    status: 'active',
    createdAt: '2024-02-28',
    owner: 'Nancy Adams',
    priority: 'low',
    deadline: '2024-07-10',
    budget: '$7,750',
    team: ['Fullstack Developer', 'UI/UX Designer', 'DevOps'],
    technologies: ['Vue.js', 'Node.js', 'MongoDB', 'AWS S3'],
    progress: 28,
    tasksCompleted: 11,
    totalTasks: 40,
    lastUpdate: '2024-03-15',
    client: 'Media Agency "Creative"',
    requirements: [
      'Support 100+ formats',
      'Auto conversion',
      'Access rights',
      'Versioning',
    ],
    goal: 'Reduce digital asset search and usage time by 60% and centralize content management',
  },
];

export const getProjectData = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockData);
    });
  });
};

export const useProjects = () => {
  const [projects, setProjects] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadProjects = async () => {
      const data = await getProjectData();
      setProjects(data);
      setLoading(false);
    };
    loadProjects();
  }, []);

  return { projects, loading, setProjects };
};
